/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframes;

/**
 *
 * @author fagueros
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuP
     */
    public MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);//para centrar la ventana
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbGestionarInventario = new javax.swing.JButton();
        jbGestionarClientes = new javax.swing.JButton();
        jbFacturar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jbGestionarEmpleados = new javax.swing.JButton();
        jlMenuDeOpciones = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jbGestionarInventario.setBackground(new java.awt.Color(0, 102, 102));
        jbGestionarInventario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbGestionarInventario.setForeground(new java.awt.Color(255, 255, 255));
        jbGestionarInventario.setText("GESTIONAR INVENTARIO");
        jbGestionarInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGestionarInventarioActionPerformed(evt);
            }
        });

        jbGestionarClientes.setBackground(new java.awt.Color(0, 102, 102));
        jbGestionarClientes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbGestionarClientes.setForeground(new java.awt.Color(255, 255, 255));
        jbGestionarClientes.setText("GESTIONAR CLIENTES");
        jbGestionarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGestionarClientesActionPerformed(evt);
            }
        });

        jbFacturar.setBackground(new java.awt.Color(0, 102, 102));
        jbFacturar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbFacturar.setForeground(new java.awt.Color(255, 255, 255));
        jbFacturar.setText("FACTURACIÓN");
        jbFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFacturarActionPerformed(evt);
            }
        });

        jbSalir.setBackground(new java.awt.Color(255, 255, 255));
        jbSalir.setText("X");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbGestionarEmpleados.setBackground(new java.awt.Color(0, 102, 102));
        jbGestionarEmpleados.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jbGestionarEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        jbGestionarEmpleados.setText("GESTIONAR EMPLEADOS");
        jbGestionarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGestionarEmpleadosActionPerformed(evt);
            }
        });

        jlMenuDeOpciones.setFont(new java.awt.Font("Hannotate TC", 3, 18)); // NOI18N
        jlMenuDeOpciones.setForeground(new java.awt.Color(0, 153, 153));
        jlMenuDeOpciones.setText("MENU DE OPCIONES");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagenMenu2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSalir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbGestionarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbGestionarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbGestionarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlMenuDeOpciones)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jbSalir)
                .addGap(91, 91, 91)
                .addComponent(jlMenuDeOpciones)
                .addGap(18, 18, 18)
                .addComponent(jbGestionarInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbGestionarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbGestionarEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed

        System.exit(0); // Para salir del programa en ejecucion.

    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbGestionarInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGestionarInventarioActionPerformed
        MenuVehiculos inv = new MenuVehiculos();
        inv.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbGestionarInventarioActionPerformed

    private void jbGestionarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGestionarClientesActionPerformed
        MenuClientes cli = new MenuClientes();
        cli.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jbGestionarClientesActionPerformed

    private void jbFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFacturarActionPerformed
        Facturacion factura = new Facturacion();
        factura.setVisible(true);
        //no cierra el menu

    }//GEN-LAST:event_jbFacturarActionPerformed

    private void jbGestionarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGestionarEmpleadosActionPerformed
       MenuEmpleados miEmpleado = new MenuEmpleados();
       miEmpleado.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jbGestionarEmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbFacturar;
    private javax.swing.JButton jbGestionarClientes;
    private javax.swing.JButton jbGestionarEmpleados;
    private javax.swing.JButton jbGestionarInventario;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel jlMenuDeOpciones;
    // End of variables declaration//GEN-END:variables
}
