/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author scont
 */
public class GestionClientes extends javax.swing.JFrame {

    private TableRowSorter trsfiltro;
    static DefaultTableModel model;
    String data[][] = {};
    String encabezado[] = {"Nombre", "Apellido", "Cédula", "Telefono", "Dirección", "E-mail"};

    static ArrayList<Cliente> arreglo;
//    static ArrayList<ContadorRegistro> arregloClient;

    /**
     * Creates new form GestionClientes
     */
    public GestionClientes() {
        arreglo = new ArrayList<>();
//        arregloCliente = new ArrayList<>();
        initComponents();

        model = new DefaultTableModel(data, encabezado);
        jtClientes.setModel(model);

        model.setColumnIdentifiers(encabezado);
//        jTableClientes.getColumnModel().getColumn(0).setPreferredWidth(200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlGestionClientes = new javax.swing.JLabel();
        jbAgregar = new javax.swing.JButton();
        jtfModificar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jlNombre = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jtfApellidos = new javax.swing.JTextField();
        jlApellidos = new javax.swing.JLabel();
        jtfCedula = new javax.swing.JTextField();
        jlCedula = new javax.swing.JLabel();
        jlTelefono = new javax.swing.JLabel();
        jtfTelefono = new javax.swing.JTextField();
        jlDireccion = new javax.swing.JLabel();
        jtfDireccion = new javax.swing.JTextField();
        jlEmail = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jbSalir = new javax.swing.JButton();
        jbMenu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtClientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jlGestionClientes.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlGestionClientes.setText("Gestión de Clientes");

        jbAgregar.setText("Agregar");

        jtfModificar.setText("Modificar");

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jlNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlNombre.setText("Nombre:");

        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });

        jtfApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfApellidosActionPerformed(evt);
            }
        });

        jlApellidos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlApellidos.setText("Apellidos:");

        jlCedula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlCedula.setText("Cédula:");

        jlTelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlTelefono.setText("Teléfono:");

        jtfTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTelefonoActionPerformed(evt);
            }
        });

        jlDireccion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlDireccion.setText("Direción:");

        jtfDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDireccionActionPerformed(evt);
            }
        });

        jlEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jlEmail.setText("E-mail:");

        jbSalir.setText("X");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbMenu.setText("Menú");
        jbMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMenuActionPerformed(evt);
            }
        });

        jtClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtClientes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlApellidos)
                                        .addGap(10, 10, 10))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jlNombre)
                                        .addGap(14, 14, 14)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(jtfApellidos)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlCedula)
                                .addGap(21, 21, 21)
                                .addComponent(jtfCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfTelefono)
                            .addComponent(jtfDireccion)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jbAgregar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jbEliminar)
                                .addGap(56, 56, 56))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(333, 333, 333)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlDireccion)
                                    .addComponent(jlEmail)
                                    .addComponent(jlTelefono))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtfModificar)
                                .addGap(0, 91, Short.MAX_VALUE))
                            .addComponent(jtfEmail))))
                .addGap(123, 123, 123))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jlGestionClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSalir))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbMenu)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlGestionClientes))
                    .addComponent(jbSalir))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTelefono)
                    .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlDireccion)
                            .addComponent(jtfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlApellidos)
                            .addComponent(jtfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCedula)
                            .addComponent(jtfCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlEmail))))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregar)
                    .addComponent(jtfModificar)
                    .addComponent(jbEliminar))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jbMenu)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMenuActionPerformed
        Menu o = new Menu();
        o.setVisible(true);
    }//GEN-LAST:event_jbMenuActionPerformed

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    private void jtfApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfApellidosActionPerformed

    private void jtfDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDireccionActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jtfTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTelefonoActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jbSalirActionPerformed

    public static void Listar() {
        DefaultListModel Md = new DefaultListModel();
        DefaultTableModel tabla = new DefaultTableModel();

        for (int i = 0; i < arreglo.size(); i++) {
            //Lee la información de los campos
            String nombre = arreglo.get(i).getNombre();
            String apellidos = arreglo.get(i).getApellidos();
            String direccion = arreglo.get(i).getDireccion();
            String telefono = arreglo.get(i).getTelefono();
            String cedula = arreglo.get(i).getCedula();
            String correoElectronico = arreglo.get(i).getEmail();

            //Almacena la información en un vector
            String datos[] = {nombre, apellidos, direccion, telefono,
                cedula, correoElectronico};
            model.addRow(datos);
        }
    }
    
     public void Limpiar() {
        this.jtfNombre.setText("");
        this.jtfApellidos.setText("");
        this.jtfDireccion.setText("");
        this.jtfTelefono.setText("");
        this.jtfCedula.setText("");
        this.jtfEmail.setText("");
        //Este metodo limpia los campos
    }

    public void BorrarTabla() {
        for (int i = 0; i < jtClientes.getRowCount(); i++) {
            model.removeRow(i);
            i -= 1;
        }
    }

    //Este metodo lee la información del archivo y la almacena en el ArrayList
    public static void CargarDatos() {
        try {
            FileInputStream Archivo = new FileInputStream("BasedeDatosClientes.dat");
            ObjectInputStream Obj = new ObjectInputStream(Archivo);
            arreglo = (ArrayList<Cliente>) Obj.readObject();
        } catch (Exception e) {

        }
//Habiendo almacenado la información del archivo en el ArrayList 
//llama al metodo listar para pasar la informacion de ArrayList a la Tabla
        Listar();
    }
    
    private void jbAgregarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        boolean siEsta = true;
        if (this.jtfNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Faltan datos!!");
        } else if (this.jtfApellidos.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Faltan datos!!");
        } else if (this.jtfDireccion.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Faltan datos!!");
        } else if (this.jtfTelefono.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Faltan datos!!");
        } else if (this.jtfEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Faltan datos!!");
        } else {
//            Cliente L = new Cliente();
//
//            boolean esta = false;
//            for (int e = 0; e < arreglo.size(); e++) {
//                //Este if valida si existe una cedula en el ArrayList contra lo que se digito 
//                //en el campo cedula, para evitar duplicados
//                if (arreglo.get(0).getCedula().equals(this.jtfCedula.getText())) {
//                    esta = true;
//                }
//            }
//
//            //Si la variable booleana esta es true quiere decir que la cedula esta duplicada
//            if (esta) {
//                JOptionPane.showMessageDialog(null,
//                        "Ya existe esa cedula en los REGISTROS", "", -1);
//            } else {
            //Se lee la información de los campos y se almacena en un ArrayList
            arreglo.add(new Cliente(jtfNombre.getText(), jtfApellidos.getText(),
                    jtfCedula.getText(), jtfTelefono.getText(),
                    jtfDireccion.getText(), jtfEmail.getText()));

            JOptionPane.showMessageDialog(null, "La información fue agregada correctamente.", "", -1);
            
            BorrarTabla();
            Listar();
            Limpiar();
        }
        GuardarDatos();


    }                                         

    public void GuardarDatos() {
        try {
            FileOutputStream Archivo = new FileOutputStream("BasedeDatosClientes.dat");
            ObjectOutputStream Obj = new ObjectOutputStream(Archivo);
            Obj.writeObject(arreglo);

            JOptionPane.showMessageDialog(null, "¡¡El archivo se guardo correctamente!!", "", -1);
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, "¡¡Upss!!,tenemos problemas con el archivo");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "¡¡Upss!!,tenemos problemas con el archivo");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAgregar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbMenu;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel jlApellidos;
    private javax.swing.JLabel jlCedula;
    private javax.swing.JLabel jlDireccion;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlGestionClientes;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlTelefono;
    private javax.swing.JTable jtClientes;
    private javax.swing.JTextField jtfApellidos;
    private javax.swing.JTextField jtfCedula;
    private javax.swing.JTextField jtfDireccion;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JButton jtfModificar;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfTelefono;
    // End of variables declaration//GEN-END:variables
}
