/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author scont
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        lbVerInventario = new javax.swing.JButton();
        jbFacturacion = new javax.swing.JButton();
        jbClientes = new javax.swing.JButton();
        jbRegistroEmpleados = new javax.swing.JButton();
        jbClientesMenbresia = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jlTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlTitulo.setText("Menú Principal");

        lbVerInventario.setBackground(new java.awt.Color(204, 204, 204));
        lbVerInventario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbVerInventario.setText("Inventario de autos ");
        lbVerInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbVerInventarioActionPerformed(evt);
            }
        });

        jbFacturacion.setBackground(new java.awt.Color(204, 204, 204));
        jbFacturacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbFacturacion.setText("Facturacion");
        jbFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFacturacionActionPerformed(evt);
            }
        });

        jbClientes.setBackground(new java.awt.Color(204, 204, 204));
        jbClientes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbClientes.setText("Clientes");
        jbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClientesActionPerformed(evt);
            }
        });

        jbRegistroEmpleados.setBackground(new java.awt.Color(153, 153, 153));
        jbRegistroEmpleados.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbRegistroEmpleados.setText("Registro empleado ");
        jbRegistroEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistroEmpleadosActionPerformed(evt);
            }
        });

        jbClientesMenbresia.setBackground(new java.awt.Color(255, 102, 102));
        jbClientesMenbresia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbClientesMenbresia.setText("Clientes con membresía VIP ");
        jbClientesMenbresia.setBorder(null);
        jbClientesMenbresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbClientesMenbresiaActionPerformed(evt);
            }
        });

        jbSalir.setBackground(new java.awt.Color(204, 204, 204));
        jbSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbSalir.setText("Cerrar Sesión");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSalir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jbClientesMenbresia, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbRegistroEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbVerInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jbFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(34, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSalir)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jlTitulo)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbVerInventario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbFacturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbRegistroEmpleados, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(jbClientesMenbresia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbSalirActionPerformed

    private void lbVerInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbVerInventarioActionPerformed
        List<Autos> vehiculo = new ArrayList();
        Autos vehiculo1 = new Motocicletas("2255", "Honda", "CRF 250 ",
            "Rojo ", "1999", "Manual ",
            "Exelente", 100.01, 250000.01,
            "Muy economico", "Sencilla", "150cc", "1 aciento",
            "1 piston");
        Autos vehiculo2 = new TodoTerreno("88774455", "Izuzu", "DMAX 4X4 ",
            "Verde  ", "2015", "Manual ", "Exelente",
            30000.44, 15000.55, "Alto", "Truck",
            "4500cc", "2 acientos ", "1200 caballos");
        Autos vehiculo3 = new Pickup("256032", "Mitsubishi", "L200 ",
            "Cafe  ", "2005", "Automatico ", "Bueno",
            15000.44, 250000.55, "Alta", "Dual",
            "3500cc", " 3 acientos ", "2 cabinas ");
        Autos vehiculo4 = new Deportivo("002512", "Bugatti", "Veyron ",
            "Azul  ", "2022", "Automatico 10 veclodiades ",
            "Exelente Nuevo ", 1000000.05, 0.0, "ALto gasto",
            "Ergonomico  ", "7000cc", "3 acientos ", "380 kilometros k/h ");
        Autos vehiculo5 = new SUV("152233", "Mazda ", "CX-30 ", "Negro   ",
            "2019", "Automatico ", "Regular  ", 100000.2,
            50000.2, "ALto gasto", "Profesional ", "4000 cc", ""
            + "4 acientos ", " 7 pasajeros ", "Tradicional");
        Autos vehiculo6 = new Microbus("556622", "Mercedes Benz", "8-150FEB ",
            "Morado   ", "2006", "Dual ", "Muy bueno   ",
            5000.2, 100000.2, "Regular ", "Van ", "6000 cc",
            "8 acientos ", " 12 pasajeros ", "Electrica ");
        Autos vehiculo7 = new Carga("668844", "Scania", "r500", "Blanco   ",
            "2012", "Manual 15 velocidades  ", "Exelente   ", 50000.232,
            1000000.05, "Versatil  ", "Doble piña  ", "135000 cc",
            "2 acientos ", " 20 toneladas ", "Carga de alto peso ");
        Autos vehiculo8 = new ATV("995544", "Yamaha", "ytz 450", "Gris   ", ""
            + "2001", "Automatico ", "Exelente   ", 5000.242,
            00.05, "4 ejes   ", "Montan ", "600 cc", "1 acientos ",
            " Si  ", "Tradicional  ");
        Autos vehiculo9 = new Sedan("886644", "Hyundai ", "grand i10", "Blanco   "
            + " ", "20016", "Automatico ", "Exelente   ", 3000.25,
            5000.0, "2 ejes    ", "Accendt  ", "1500 cc",
            "3 acientos ", " 14  ", "Electrico  ");

        vehiculo.add(vehiculo1);
        vehiculo.add(vehiculo2);
        vehiculo.add(vehiculo3);
        vehiculo.add(vehiculo4);
        vehiculo.add(vehiculo5);
        vehiculo.add(vehiculo6);
        vehiculo.add(vehiculo7);
        vehiculo.add(vehiculo8);
        vehiculo.add(vehiculo9);

        JOptionPane.showMessageDialog(null,
            "Bienvenidos a venta de autos, estos son nuestros vehiculos disponibles");

        for (Autos vehiculos : vehiculo) {
            //            JOptionPane.showMessageDialog(null, "Siguiente auto disponible ");
            JOptionPane.showMessageDialog(null, vehiculos.mostrarDatos());
        }

    }//GEN-LAST:event_lbVerInventarioActionPerformed

    private void jbFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFacturacionActionPerformed
        Facturacion o = new Facturacion();
        o.setVisible(true);
    }//GEN-LAST:event_jbFacturacionActionPerformed

    private void jbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClientesActionPerformed
        GestionClientes b = new GestionClientes();
        b.setVisible(true);
    }//GEN-LAST:event_jbClientesActionPerformed

    private void jbRegistroEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistroEmpleadosActionPerformed
        List<Persona> empleado = new ArrayList();
        Persona empleado1 = new Empleado(475000.00, "Ventas",
            "Rafael ", "Herrero", "3-5689-5321",
            "5698-4532", "San Isidro, Heredia",
            "rherrero@vehiculoscr.com");
        Persona empleado2 = new Empleado(450000.00, "Ventas",
            "Adrian", "Ramos", "5-5645-9875",
            "6598-2156", "San Isidro, Heredia",
            "aramos@vehiculoscr.com");
        Persona empleado3 = new Empleado(700000.00, "Administracion",
            "Rosario", "Moreno", "7-3654-7541",
            "7856-3216", "Santa Ana, Escazú",
            "emoreno@vehiculoscr.com");

        empleado.add(empleado1);
        empleado.add(empleado2);
        empleado.add(empleado3);

        for (Persona empleados : empleado) {
            //            JOptionPane.showMessageDialog(null, "Lista de Empleados ");
            JOptionPane.showMessageDialog(null, empleados.mostrarDatos());
        }
    }//GEN-LAST:event_jbRegistroEmpleadosActionPerformed

    private void jbClientesMenbresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbClientesMenbresiaActionPerformed
        List<Persona> cliente = new ArrayList();
        Persona cliente1 = new Cliente("Marco", "Polo", "1-1234-1234",
            "5555-5555", "Santa Rosa, Heredia", "marcopolo33@live.com");
        Persona cliente2 = new Cliente("Rebeca ", "Gómez ", "4-63145-2456",
            "7777-7777", "Turrialba, Cartago", "rebe27@radiodos.com");
        Persona cliente3 = new Cliente("Matías ", "Ortega ", "5-3968-6547",
            "5555-5555", "Santa Rosa, Heredia", "matías.ortega87@mitierra.cr");
        Persona cliente4 = new Cliente("Juan Pablo", "Muñoz ", "2-2365-7412",
            "5555-5555", "Santa Rosa, Heredia", "jpmunos112@outlook.com");

        cliente.add(cliente1);
        cliente.add(cliente2);
        cliente.add(cliente3);
        cliente.add(cliente4);

        for (Persona clientes : cliente) {
            //            JOptionPane.showMessageDialog(null, "Lista de Clientes ");
            JOptionPane.showMessageDialog(null, clientes.mostrarDatos());
        }
    }//GEN-LAST:event_jbClientesMenbresiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbClientes;
    private javax.swing.JButton jbClientesMenbresia;
    private javax.swing.JButton jbFacturacion;
    private javax.swing.JButton jbRegistroEmpleados;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JButton lbVerInventario;
    // End of variables declaration//GEN-END:variables
}
